### ISSUE TITLE
Text errors/translation

### ISSUE THREAD

**Issue by SteveWasT** [stevejcl/PhotoPolarAlign#2]
Just a minor note you have a few spellings to correct 
 
'positionning' which should be 'positioning'

'exposition' which is possibly better as 'exposure'

**Comment by stevejcl** [comment]
sorry, english is not my native language

**Comment by SteveWasT** [comment]
No need to apologise we Brits are probably the worst at non-native languages and have the weirdest spelling rules. Happy  to help with what I little I can.

**Comment by SteveWasT** [comment]
All fixed now.
