### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x80' in file

### ISSUE THREAD

**Issue by macicco** [stevejcl/PhotoPolarAlign#3]
Hi!

I followed instructions and extract , compiling the files, for UBUNTU 2.0, but when I do:

`python3 ./PPA` command immediatly the following error :

SyntaxError: Non-UTF-8 code starting with '\x80' in file ./PPA on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by stevejcl** [comment]
yes, we need some UTF8 config files from astropy, but if we use the setup.py it convert them so I use the original ones and do a copy but I have missed to push the Install directory !

**Comment by macicco** [comment]
Yes it is ok, now. Thanks!
